### ISSUE TITLE
libencoding.so has text relocations

### ISSUE THREAD

**Issue by UngureanEugen** [arjan/instantVideoRecord#1]
Hi, thanks for your library. 
In log we receive this message -> 

```
"libencoding.so has text relocations. This is wasting memory and is a security risk. Please fix"
```

Is it real problem and if yes how to fix it ? 
Thanks

**Comment by arjan** [comment]
This is a good question, to which I don't know the answer.

Maybe this helps:
http://stackoverflow.com/questions/20141538/mylib-so-has-text-relocations-this-is-wasting-memory-and-is-a-security-risk-pl

**Comment by UngureanEugen** [comment]
Thanks
